// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Engineering
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject engineeringMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Engineering";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EngineeringName("EngineeringName"),
		Number("Number"),
		Range("Range"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		Outline("Outline"),
		Meno("Meno"),
		Engineering_Project("MyFirstModule.Engineering_Project");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Engineering(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Engineering"));
	}

	protected Engineering(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject engineeringMendixObject)
	{
		if (engineeringMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Engineering", engineeringMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Engineering");

		this.engineeringMendixObject = engineeringMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Engineering.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Engineering initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Engineering.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Engineering initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Engineering(context, mendixObject);
	}

	public static myfirstmodule.proxies.Engineering load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Engineering.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Engineering> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Engineering> result = new java.util.ArrayList<myfirstmodule.proxies.Engineering>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Engineering" + xpathConstraint))
			result.add(myfirstmodule.proxies.Engineering.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EngineeringName
	 */
	public final java.lang.String getEngineeringName()
	{
		return getEngineeringName(getContext());
	}

	/**
	 * @param context
	 * @return value of EngineeringName
	 */
	public final java.lang.String getEngineeringName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EngineeringName.toString());
	}

	/**
	 * Set value of EngineeringName
	 * @param engineeringname
	 */
	public final void setEngineeringName(java.lang.String engineeringname)
	{
		setEngineeringName(getContext(), engineeringname);
	}

	/**
	 * Set value of EngineeringName
	 * @param context
	 * @param engineeringname
	 */
	public final void setEngineeringName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String engineeringname)
	{
		getMendixObject().setValue(context, MemberNames.EngineeringName.toString(), engineeringname);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.String getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.String getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.String number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Range
	 */
	public final java.lang.String getRange()
	{
		return getRange(getContext());
	}

	/**
	 * @param context
	 * @return value of Range
	 */
	public final java.lang.String getRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Range.toString());
	}

	/**
	 * Set value of Range
	 * @param range
	 */
	public final void setRange(java.lang.String range)
	{
		setRange(getContext(), range);
	}

	/**
	 * Set value of Range
	 * @param context
	 * @param range
	 */
	public final void setRange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String range)
	{
		getMendixObject().setValue(context, MemberNames.Range.toString(), range);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of Outline
	 */
	public final java.lang.String getOutline()
	{
		return getOutline(getContext());
	}

	/**
	 * @param context
	 * @return value of Outline
	 */
	public final java.lang.String getOutline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outline.toString());
	}

	/**
	 * Set value of Outline
	 * @param outline
	 */
	public final void setOutline(java.lang.String outline)
	{
		setOutline(getContext(), outline);
	}

	/**
	 * Set value of Outline
	 * @param context
	 * @param outline
	 */
	public final void setOutline(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outline)
	{
		getMendixObject().setValue(context, MemberNames.Outline.toString(), outline);
	}

	/**
	 * @return value of Meno
	 */
	public final java.lang.String getMeno()
	{
		return getMeno(getContext());
	}

	/**
	 * @param context
	 * @return value of Meno
	 */
	public final java.lang.String getMeno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Meno.toString());
	}

	/**
	 * Set value of Meno
	 * @param meno
	 */
	public final void setMeno(java.lang.String meno)
	{
		setMeno(getContext(), meno);
	}

	/**
	 * Set value of Meno
	 * @param context
	 * @param meno
	 */
	public final void setMeno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String meno)
	{
		getMendixObject().setValue(context, MemberNames.Meno.toString(), meno);
	}

	/**
	 * @return value of Engineering_Project
	 */
	public final myfirstmodule.proxies.Project getEngineering_Project() throws com.mendix.core.CoreException
	{
		return getEngineering_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of Engineering_Project
	 */
	public final myfirstmodule.proxies.Project getEngineering_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Engineering_Project.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Engineering_Project
	 * @param engineering_project
	 */
	public final void setEngineering_Project(myfirstmodule.proxies.Project engineering_project)
	{
		setEngineering_Project(getContext(), engineering_project);
	}

	/**
	 * Set value of Engineering_Project
	 * @param context
	 * @param engineering_project
	 */
	public final void setEngineering_Project(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Project engineering_project)
	{
		if (engineering_project == null)
			getMendixObject().setValue(context, MemberNames.Engineering_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Engineering_Project.toString(), engineering_project.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return engineeringMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Engineering that = (myfirstmodule.proxies.Engineering) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Engineering";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
