// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum ProjectType
{
	Normal(new java.lang.String[][] { new java.lang.String[] { "en_US", "工民建" }, new java.lang.String[] { "zh_CN", "工民建" } }),
	Hydro(new java.lang.String[][] { new java.lang.String[] { "en_US", "水电水利" }, new java.lang.String[] { "zh_CN", "水电水利" } }),
	Road(new java.lang.String[][] { new java.lang.String[] { "en_US", "公路" }, new java.lang.String[] { "zh_CN", "公路交通" } }),
	MunicipalTraffic(new java.lang.String[][] { new java.lang.String[] { "en_US", "市政交通" }, new java.lang.String[] { "zh_CN", "市政交通" } }),
	Railway(new java.lang.String[][] { new java.lang.String[] { "en_US", "铁路" }, new java.lang.String[] { "zh_CN", "铁路" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ProjectType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
